### ISSUE TITLE
README.md title URL points to another site

### ISSUE THREAD

**Issue by KrishMunot** [facebook/makeitopen#15]
The [makeitopen.com](makeitopen.com) title in the README file is pointing to some path in the same repo, which is weird after I cross checked its markdown and it clearly should point to its actual URL.

Please fix this and enlighten me about how this is happening.

**Comment by KrishMunot** [comment]
Could you look into this @matthewjohnston4 ?

**Comment by matthewjohnston4** [comment]
Fixed!
