### ISSUE TITLE
Container components links are broken

### ISSUE THREAD

**Issue by montogeek** [facebook/makeitopen#2]
Please complete the information below:

# Where is the problem?

In the third page of the guide [Integrating Data with React Native](http://makeitopen.com/tutorials/building-the-f8-app/data/), there are 2 links pointing to (http://makeitopen.com/#containercomponents) which is a broken link, it does not exists.

I guess if they mean to link to:
- https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.2ahd3vm0n
- http://redux.js.org/docs/basics/UsageWithReact.html#container-components
- https://egghead.io/lessons/javascript-redux-extracting-container-components-filterlink?series=getting-started-with-redux

# What is the problem?

Container components links are broken

--------------------------------
Please don't change anything below this point.
--------------------------------

 - Page requested: /tutorials/building-the-f8-app/data/
 - Page requested at: Wed Apr 13 17:45:47 2016
 - Doc: Integrating Data with React Native

--------------------------------
I can submit a PR to correct both links!

PD: Thanks for the guide, extremely useful and informative!

**Comment by matthewjohnston4** [comment]
Thanks, seems that Jekyll didn't like the in-page anchor link!
