### ISSUE TITLE
Comments section, or some way for us to ask questions

### ISSUE THREAD

**Issue by pavlelekic** [facebook/makeitopen#20]
Hi guys,
While studying f8app, some of the things were not clear to me, like why you wrote some parts the way you did, why are some pieces of code there, what is it for etc. I had a lot of questions, and no way to ask. There is no comments section on the site, and github doesn't have a discussion tab. Maybe I could have posted a question on stackoverflow, but how probable is that the author will see that and respond?

I'm grateful for all the work you did and for sharing the app and making it open, I learned a lot anyway. It just could have been a little better if there was a discussion tab, or comments section.

**Comment by caabernathy** [comment]
In the latest release, we've decided to try this out by adding a discussion label and an issue for each page in the tutorial, see https://github.com/facebook/makeitopen/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion. We'll keep these open so this can be discussed publicly.
