### ISSUE TITLE
Use F8app to document NavigationExperimental+Redux usage

### ISSUE THREAD

**Issue by mikelambert** [facebook/makeitopen#7]
F8 was built with the regular Navigator, but from https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/NavigationOverview.md it says "Facebook is transitioning from Navigator to NavigationExperimental, which will be the supported navigation library going forward."

Currently, Redux+NavigationExperimental tutorials are quite sparse, so seeing a real-world beautiful use case like the redux-based f8 migrate would be a big help (to me, at least, and I suspect others as well).

It's possible NavigationExperimental isn't yet API-stable enough for a migration, but hopefully this can be a tracking issue for that migration (or the reasons not to migrate), as I'd be very interested in following along in either case.

**Comment by matthewjohnston4** [comment]
Could you file an issue on the [F8 app's repo](https://github.com/fbsamples/f8app/) for this? We'll need the app code updated before we could do any documentation around it :)

**Comment by mikelambert** [comment]
Oh woops, didn't check and mistakenly thought this was the f8 repo! Thanks, filed as https://github.com/fbsamples/f8app/issues/8

**Comment by caabernathy** [comment]
Following the thread on this, the migration to Navigation Experimental never happened and [React Navigation](https://reactnavigation.org/) is instead one of the recommended approaches. I'm going to close this issue. Perhaps if someone can put up a pull request moving to the new navigator, a corresponding, fresh documentation issue can be opened or it can be part of that work.
