### ISSUE TITLE
The Design Iteration Cycle

### ISSUE THREAD

**Issue by liaohuqiu** [facebook/makeitopen#9]
> When you’re building any kind of app, mobile or web, it can be painful to quickly tweak and adjust UI elements. If an engineer and designer are working together, this can slow the whole process down.

Why it will not be faster then engineer and designer are working together?

**Comment by caabernathy** [comment]
What this was trying to compare is if the engineer is also functioning as a designer it can be faster than having to wait for a separate designer to see the UI, suggest tweaks, and have the engineer implement them.

If you have further questions around the design, be sure to leave a comment here: https://github.com/facebook/makeitopen/issues/69
